### PR TITLE
Add lifecycle order table for quicker scanability of capabilities

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
I find this layout of data easier to read. :man_shrugging: maybe other people do to?

Supercedes: https://github.com/chancancode/ember-class-based-modifier/pull/1

@chancancode / @sukima looks like some changes haven't made it in to master quite yet?

### CODE REVIEW

**Comment by chancancode** [comment]
@NullVoxPopuli it should be all good now!

**Comment by chancancode** [comment]
@NullVoxPopuli can you "rebase" on master?

**Comment by NullVoxPopuli** [comment]
Divergence was great. Started over + copy paste. lol

**Review by chancancode — APPROVED** [review]
Awesome!

**Comment by chancancode** [comment]
Thank you! Sorry about the churn!

**Pull request merged**
